/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117615-gbaa23e40c1-20241021"
#endif /* AVUTIL_FFVERSION_H */
